In [11]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movies.csv').merge(pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ratings.csv'), on='movieId', how="left")
df[df['rating']==5.0]['title'].value_counts().head(1)

title
Shawshank Redemption, The (1994)    153
Name: count, dtype: int64

In [15]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/power.csv')
baltic_power = df[(df['country'].isin(['Lithuania', 'Latvia', 'Estonia'])) & (df['category'].isin([4, 12, 21])) & (df['year'] > 2005) & (df['year'] < 2010) & (df['quantity'] > 0)]
baltic_power['quantity'].sum()

164555.0

In [27]:
df = pd.read_html('https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html')[0]
df

,Функция или метод,Назначение
0,"S = 'str'; S = ""str""; S = '''str'''; S = """"""st...",Литералы строк
1,"S = ""s\np\ta\nbbb""",Экранированные последовательности
2,"S = r""C:\temp\new""",Неформатированные строки (подавляют экранирова...
3,"S = b""byte""",Строка байтов
4,S1 + S2,Конкатенация (сложение строк)
5,S1 * 3,Повторение строки
6,S[i],Обращение по индексу
7,S[i:j:step],Извлечение среза
8,len(S),Длина строки
9,"S.find(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пер...
10,"S.rfind(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пос...
11,"S.index(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пер...
12,"S.rindex(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пос...
13,"S.replace(шаблон, замена[, maxcount])",Замена шаблона на замену. maxcount ограничивае...
14,S.split(символ),Разбиение строки по разделителю
15,S.isdigit(),Состоит ли строка из цифр
16,S.isalpha(),Состоит ли строка из букв
17,S.isalnum(),Состоит ли строка из цифр или букв
18,S.islower(),Состоит ли строка из символов в нижнем регистре
19,S.isupper(),Состоит ли строка из символов в верхнем регистре
20,S.isspace(),Состоит ли строка из неотображаемых символов (...
21,S.istitle(),Начинаются ли слова в строке с заглавной буквы
22,S.upper(),Преобразование строки к верхнему регистру
23,S.lower(),Преобразование строки к нижнему регистру
24,S.startswith(str),Начинается ли строка S с шаблона str
25,S.endswith(str),Заканчивается ли строка S шаблоном str
26,S.join(список),Сборка строки из списка с разделителем S
27,ord(символ),Символ в его код ASCII
28,chr(число),Код ASCII в символ
29,S.capitalize(),Переводит первый символ строки в верхний регис...
30,"S.center(width, [fill])","Возвращает отцентрованную строку, по краям кот..."
31,"S.count(str, [start],[end])",Возвращает количество непересекающихся вхожден...
32,S.expandtabs([tabsize]),"Возвращает копию строки, в которой все символы..."
33,S.lstrip([chars]),Удаление пробельных символов в начале строки
34,S.rstrip([chars]),Удаление пробельных символов в конце строки
35,S.strip([chars]),Удаление пробельных символов в начале и в конц...
36,S.partition(шаблон),"Возвращает кортеж, содержащий часть перед перв..."
37,S.rpartition(sep),"Возвращает кортеж, содержащий часть перед посл..."
38,S.swapcase(),"Переводит символы нижнего регистра в верхний, ..."
39,S.title(),Первую букву каждого слова переводит в верхний...
40,S.zfill(width),"Делает длину строки не меньшей width, по необх..."
41,"S.ljust(width, fillchar="" "")","Делает длину строки не меньшей width, по необх..."
42,"S.rjust(width, fillchar="" "")","Делает длину строки не меньшей width, по необх..."
43,"S.format(*args, **kwargs)",Форматирование строки