In [1]:
import pandas as pd

ratings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ratings.csv')

def film_classificator(line):
    if line['rating'] <= 2:
        return 'Низкий рейтинг'
    elif 2 < line['rating'] <= 4:
        return 'Средний рейтинг'
    else:
        return 'Высокий рейтинг'

ratings['film_class'] = ratings.apply(film_classificator, axis=1)
ratings.head()

   userId  movieId  rating  timestamp       film_class
0       1        1     4.0  964982703  Средний рейтинг
1       1        3     4.0  964981247  Средний рейтинг
2       1        6     4.0  964982224  Средний рейтинг
3       1       47     5.0  964983815  Высокий рейтинг
4       1       50     5.0  964982931  Высокий рейтинг

In [ ]:
geo_data = {

'Центр':['москва', 'тула', 'ярославль'],

'Северо-Запад':['петербург', 'псков', 'мурманск'],

'Дальний Восток':['владивосток', 'сахалин', 'хабаровск']

}

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/keywords.csv')

def set_region(row):
    q = row['keyword'].split()
    for region, city_list in geo_data.items():
        for word in q:
            if word in city_list:
                return region
    return 'undefined'


df['region'] = df.apply(set_region, axis=1)
df[(df['region']!='undefined')].head(10)

                       keyword   shows          region
0                 авито москва  979292           Центр
127               авито москва  979292           Центр
370   авито ру санкт петербург  425134    Северо-Запад
849            авито ярославль  209581           Центр
1063       фарпост владивосток  176951  Дальний Восток
1236      банк санкт петербург  174375    Северо-Запад
1259                    москва  153050           Центр
1346           санкт петербург  144232    Северо-Запад
1396           гисметео москва  140279           Центр
1482          госуслуги москва  133061           Центр

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movies.csv')
ratings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ratings.csv')

years_list = [str(year) for year in range(1950, 2011)]

def get_production_year(row):
    for year in years_list:
        if year in row['title']:
            return year
    return 1900

movies['year'] = movies.apply(get_production_year, axis=1)
data = ratings.merge(movies, on='movieId', how="left")
data[['year', 'rating']].groupby('year').mean().sort_values('rating', ascending=False)

        rating
year
1957  4.039535
1954  4.009191
1962  3.969466
1952  3.953125
1972  3.944293
...        ...
2000  3.398922
2005  3.359976
1992  3.353555
1997  3.347241
1996  3.335329

[62 rows x 1 columns]